// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdWBRlk5Bka8VjbDkX3JR9W8qrIWGHUfE',
    appId: '1:816087388737:android:1ca2e3d59390e0c1536cc0',
    messagingSenderId: '816087388737',
    projectId: 'creator-resource-hub',
    storageBucket: 'creator-resource-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR-ZyauLDCIpjRbsLabjSI5yJ2Ed_lNl8',
    appId: '1:816087388737:ios:bf851edfd9d7fa9a536cc0',
    messagingSenderId: '816087388737',
    projectId: 'creator-resource-hub',
    storageBucket: 'creator-resource-hub.firebasestorage.app',
    iosBundleId: 'com.heintun.creatorresourcehub',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ip6Ci_Jb8jsFNsPwnk96h7TavIJLVrw',
    appId: '1:816087388737:web:1e36ff240e31cb64536cc0',
    messagingSenderId: '816087388737',
    projectId: 'creator-resource-hub',
    authDomain: 'creator-resource-hub.firebaseapp.com',
    storageBucket: 'creator-resource-hub.firebasestorage.app',
    measurementId: 'G-YTTMZDNZ2Z',
  );
}
